//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:02 AM MESZ 
//


package de.og.orgdatenreader.infra.bestriebsstellen;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BTRST_ANZEIGEKATEGORIE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_BAHNSTELLENNR" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_BST_UIC_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_BZ_ORTSBEZEICHNER" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_DS100" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_EXTERN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_NAME_16" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_NAME_40" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_POSITION_X" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_POSITION_X_LEIDAS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_POSITION_Y" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BTRST_POSITION_Y_LEIDAS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BZ_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="EBU_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OE_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OE_KEY_IST_BENACHBART_ZU" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWBETRZ_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWBTRSTA_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWBUNDESL_KEY_LIEGT_IN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWZLST_KEY_GEHOERT_ZU" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Format")
public class Format {

    @XmlAttribute(name = "BTRST_ANZEIGEKATEGORIE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstanzeigekategorie;
    @XmlAttribute(name = "BTRST_BAHNSTELLENNR", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstbahnstellennr;
    @XmlAttribute(name = "BTRST_BST_UIC_NR", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstbstuicnr;
    @XmlAttribute(name = "BTRST_BZ_ORTSBEZEICHNER", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstbzortsbezeichner;
    @XmlAttribute(name = "BTRST_DS100", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstds100;
    @XmlAttribute(name = "BTRST_EXTERN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstexternkey;
    @XmlAttribute(name = "BTRST_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstkey;
    @XmlAttribute(name = "BTRST_NAME_16", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstname16;
    @XmlAttribute(name = "BTRST_NAME_40", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstname40;
    @XmlAttribute(name = "BTRST_POSITION_X", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstpositionx;
    @XmlAttribute(name = "BTRST_POSITION_X_LEIDAS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstpositionxleidas;
    @XmlAttribute(name = "BTRST_POSITION_Y", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstpositiony;
    @XmlAttribute(name = "BTRST_POSITION_Y_LEIDAS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstpositionyleidas;
    @XmlAttribute(name = "BZ_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bzkey;
    @XmlAttribute(name = "EBU_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String ebukey;
    @XmlAttribute(name = "OE_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String oekey;
    @XmlAttribute(name = "OE_KEY_IST_BENACHBART_ZU", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String oekeyistbenachbartzu;
    @XmlAttribute(name = "SWBETRZ_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swbetrzkey;
    @XmlAttribute(name = "SWBTRSTA_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swbtrstakey;
    @XmlAttribute(name = "SWBUNDESL_KEY_LIEGT_IN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swbundeslkeyliegtin;
    @XmlAttribute(name = "SWZLST_KEY_GEHOERT_ZU", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swzlstkeygehoertzu;

    /**
     * Gets the value of the btrstanzeigekategorie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTANZEIGEKATEGORIE() {
        return btrstanzeigekategorie;
    }

    /**
     * Sets the value of the btrstanzeigekategorie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTANZEIGEKATEGORIE(String value) {
        this.btrstanzeigekategorie = value;
    }

    /**
     * Gets the value of the btrstbahnstellennr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTBAHNSTELLENNR() {
        return btrstbahnstellennr;
    }

    /**
     * Sets the value of the btrstbahnstellennr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTBAHNSTELLENNR(String value) {
        this.btrstbahnstellennr = value;
    }

    /**
     * Gets the value of the btrstbstuicnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTBSTUICNR() {
        return btrstbstuicnr;
    }

    /**
     * Sets the value of the btrstbstuicnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTBSTUICNR(String value) {
        this.btrstbstuicnr = value;
    }

    /**
     * Gets the value of the btrstbzortsbezeichner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTBZORTSBEZEICHNER() {
        return btrstbzortsbezeichner;
    }

    /**
     * Sets the value of the btrstbzortsbezeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTBZORTSBEZEICHNER(String value) {
        this.btrstbzortsbezeichner = value;
    }

    /**
     * Gets the value of the btrstds100 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTDS100() {
        return btrstds100;
    }

    /**
     * Sets the value of the btrstds100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTDS100(String value) {
        this.btrstds100 = value;
    }

    /**
     * Gets the value of the btrstexternkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTEXTERNKEY() {
        return btrstexternkey;
    }

    /**
     * Sets the value of the btrstexternkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTEXTERNKEY(String value) {
        this.btrstexternkey = value;
    }

    /**
     * Gets the value of the btrstkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTKEY() {
        return btrstkey;
    }

    /**
     * Sets the value of the btrstkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTKEY(String value) {
        this.btrstkey = value;
    }

    /**
     * Gets the value of the btrstname16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTNAME16() {
        return btrstname16;
    }

    /**
     * Sets the value of the btrstname16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTNAME16(String value) {
        this.btrstname16 = value;
    }

    /**
     * Gets the value of the btrstname40 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTNAME40() {
        return btrstname40;
    }

    /**
     * Sets the value of the btrstname40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTNAME40(String value) {
        this.btrstname40 = value;
    }

    /**
     * Gets the value of the btrstpositionx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTPOSITIONX() {
        return btrstpositionx;
    }

    /**
     * Sets the value of the btrstpositionx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTPOSITIONX(String value) {
        this.btrstpositionx = value;
    }

    /**
     * Gets the value of the btrstpositionxleidas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTPOSITIONXLEIDAS() {
        return btrstpositionxleidas;
    }

    /**
     * Sets the value of the btrstpositionxleidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTPOSITIONXLEIDAS(String value) {
        this.btrstpositionxleidas = value;
    }

    /**
     * Gets the value of the btrstpositiony property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTPOSITIONY() {
        return btrstpositiony;
    }

    /**
     * Sets the value of the btrstpositiony property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTPOSITIONY(String value) {
        this.btrstpositiony = value;
    }

    /**
     * Gets the value of the btrstpositionyleidas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTPOSITIONYLEIDAS() {
        return btrstpositionyleidas;
    }

    /**
     * Sets the value of the btrstpositionyleidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTPOSITIONYLEIDAS(String value) {
        this.btrstpositionyleidas = value;
    }

    /**
     * Gets the value of the bzkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBZKEY() {
        return bzkey;
    }

    /**
     * Sets the value of the bzkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBZKEY(String value) {
        this.bzkey = value;
    }

    /**
     * Gets the value of the ebukey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBUKEY() {
        return ebukey;
    }

    /**
     * Sets the value of the ebukey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBUKEY(String value) {
        this.ebukey = value;
    }

    /**
     * Gets the value of the oekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOEKEY() {
        return oekey;
    }

    /**
     * Sets the value of the oekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOEKEY(String value) {
        this.oekey = value;
    }

    /**
     * Gets the value of the oekeyistbenachbartzu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOEKEYISTBENACHBARTZU() {
        return oekeyistbenachbartzu;
    }

    /**
     * Sets the value of the oekeyistbenachbartzu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOEKEYISTBENACHBARTZU(String value) {
        this.oekeyistbenachbartzu = value;
    }

    /**
     * Gets the value of the swbetrzkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWBETRZKEY() {
        return swbetrzkey;
    }

    /**
     * Sets the value of the swbetrzkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWBETRZKEY(String value) {
        this.swbetrzkey = value;
    }

    /**
     * Gets the value of the swbtrstakey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWBTRSTAKEY() {
        return swbtrstakey;
    }

    /**
     * Sets the value of the swbtrstakey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWBTRSTAKEY(String value) {
        this.swbtrstakey = value;
    }

    /**
     * Gets the value of the swbundeslkeyliegtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWBUNDESLKEYLIEGTIN() {
        return swbundeslkeyliegtin;
    }

    /**
     * Sets the value of the swbundeslkeyliegtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWBUNDESLKEYLIEGTIN(String value) {
        this.swbundeslkeyliegtin = value;
    }

    /**
     * Gets the value of the swzlstkeygehoertzu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWZLSTKEYGEHOERTZU() {
        return swzlstkeygehoertzu;
    }

    /**
     * Sets the value of the swzlstkeygehoertzu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWZLSTKEYGEHOERTZU(String value) {
        this.swzlstkeygehoertzu = value;
    }

}
