//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:04 AM MESZ 
//


package de.og.orgdatenreader.infra.spurplanknoten;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BTRST_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_ABGRKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_DGKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_ELEMENTNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_EXTERN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_FUNKTIONSGRUPPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_GEKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY_HAT_ALS_BEGINN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY_IST_NACHBAR1_VON" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY_IST_NACHBAR2_VON" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY_IST_NACHBAR3_VON" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KM_LAGE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_LFD_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_OBERFL_BEZEICHNER" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_ORTSBEZEICHNER" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_TYP" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STR_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Format")
public class Format {

    @XmlAttribute(name = "BTRST_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String btrstkey;
    @XmlAttribute(name = "SPLKN_ABGRKN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknabgrknkey;
    @XmlAttribute(name = "SPLKN_DGKN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splkndgknkey;
    @XmlAttribute(name = "SPLKN_ELEMENTNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknelementname;
    @XmlAttribute(name = "SPLKN_EXTERN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknexternkey;
    @XmlAttribute(name = "SPLKN_FUNKTIONSGRUPPE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknfunktionsgruppe;
    @XmlAttribute(name = "SPLKN_GEKN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splkngeknkey;
    @XmlAttribute(name = "SPLKN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkey;
    @XmlAttribute(name = "SPLKN_KEY_HAT_ALS_BEGINN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkeyhatalsbeginn;
    @XmlAttribute(name = "SPLKN_KEY_IST_NACHBAR1_VON", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkeyistnachbar1VON;
    @XmlAttribute(name = "SPLKN_KEY_IST_NACHBAR2_VON", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkeyistnachbar2VON;
    @XmlAttribute(name = "SPLKN_KEY_IST_NACHBAR3_VON", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkeyistnachbar3VON;
    @XmlAttribute(name = "SPLKN_KM_LAGE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknkmlage;
    @XmlAttribute(name = "SPLKN_LFD_NR", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknlfdnr;
    @XmlAttribute(name = "SPLKN_NAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknname;
    @XmlAttribute(name = "SPLKN_OBERFL_BEZEICHNER", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknoberflbezeichner;
    @XmlAttribute(name = "SPLKN_ORTSBEZEICHNER", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splknortsbezeichner;
    @XmlAttribute(name = "SPLKN_TYP", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String splkntyp;
    @XmlAttribute(name = "STR_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strkey;

    /**
     * Gets the value of the btrstkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBTRSTKEY() {
        return btrstkey;
    }

    /**
     * Sets the value of the btrstkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBTRSTKEY(String value) {
        this.btrstkey = value;
    }

    /**
     * Gets the value of the splknabgrknkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNABGRKNKEY() {
        return splknabgrknkey;
    }

    /**
     * Sets the value of the splknabgrknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNABGRKNKEY(String value) {
        this.splknabgrknkey = value;
    }

    /**
     * Gets the value of the splkndgknkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNDGKNKEY() {
        return splkndgknkey;
    }

    /**
     * Sets the value of the splkndgknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNDGKNKEY(String value) {
        this.splkndgknkey = value;
    }

    /**
     * Gets the value of the splknelementname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNELEMENTNAME() {
        return splknelementname;
    }

    /**
     * Sets the value of the splknelementname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNELEMENTNAME(String value) {
        this.splknelementname = value;
    }

    /**
     * Gets the value of the splknexternkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNEXTERNKEY() {
        return splknexternkey;
    }

    /**
     * Sets the value of the splknexternkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNEXTERNKEY(String value) {
        this.splknexternkey = value;
    }

    /**
     * Gets the value of the splknfunktionsgruppe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNFUNKTIONSGRUPPE() {
        return splknfunktionsgruppe;
    }

    /**
     * Sets the value of the splknfunktionsgruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNFUNKTIONSGRUPPE(String value) {
        this.splknfunktionsgruppe = value;
    }

    /**
     * Gets the value of the splkngeknkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNGEKNKEY() {
        return splkngeknkey;
    }

    /**
     * Sets the value of the splkngeknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNGEKNKEY(String value) {
        this.splkngeknkey = value;
    }

    /**
     * Gets the value of the splknkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKEY() {
        return splknkey;
    }

    /**
     * Sets the value of the splknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKEY(String value) {
        this.splknkey = value;
    }

    /**
     * Gets the value of the splknkeyhatalsbeginn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKEYHATALSBEGINN() {
        return splknkeyhatalsbeginn;
    }

    /**
     * Sets the value of the splknkeyhatalsbeginn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKEYHATALSBEGINN(String value) {
        this.splknkeyhatalsbeginn = value;
    }

    /**
     * Gets the value of the splknkeyistnachbar1VON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKEYISTNACHBAR1VON() {
        return splknkeyistnachbar1VON;
    }

    /**
     * Sets the value of the splknkeyistnachbar1VON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKEYISTNACHBAR1VON(String value) {
        this.splknkeyistnachbar1VON = value;
    }

    /**
     * Gets the value of the splknkeyistnachbar2VON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKEYISTNACHBAR2VON() {
        return splknkeyistnachbar2VON;
    }

    /**
     * Sets the value of the splknkeyistnachbar2VON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKEYISTNACHBAR2VON(String value) {
        this.splknkeyistnachbar2VON = value;
    }

    /**
     * Gets the value of the splknkeyistnachbar3VON property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKEYISTNACHBAR3VON() {
        return splknkeyistnachbar3VON;
    }

    /**
     * Sets the value of the splknkeyistnachbar3VON property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKEYISTNACHBAR3VON(String value) {
        this.splknkeyistnachbar3VON = value;
    }

    /**
     * Gets the value of the splknkmlage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNKMLAGE() {
        return splknkmlage;
    }

    /**
     * Sets the value of the splknkmlage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNKMLAGE(String value) {
        this.splknkmlage = value;
    }

    /**
     * Gets the value of the splknlfdnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNLFDNR() {
        return splknlfdnr;
    }

    /**
     * Sets the value of the splknlfdnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNLFDNR(String value) {
        this.splknlfdnr = value;
    }

    /**
     * Gets the value of the splknname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNNAME() {
        return splknname;
    }

    /**
     * Sets the value of the splknname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNNAME(String value) {
        this.splknname = value;
    }

    /**
     * Gets the value of the splknoberflbezeichner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNOBERFLBEZEICHNER() {
        return splknoberflbezeichner;
    }

    /**
     * Sets the value of the splknoberflbezeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNOBERFLBEZEICHNER(String value) {
        this.splknoberflbezeichner = value;
    }

    /**
     * Gets the value of the splknortsbezeichner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNORTSBEZEICHNER() {
        return splknortsbezeichner;
    }

    /**
     * Sets the value of the splknortsbezeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNORTSBEZEICHNER(String value) {
        this.splknortsbezeichner = value;
    }

    /**
     * Gets the value of the splkntyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPLKNTYP() {
        return splkntyp;
    }

    /**
     * Sets the value of the splkntyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPLKNTYP(String value) {
        this.splkntyp = value;
    }

    /**
     * Gets the value of the strkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRKEY() {
        return strkey;
    }

    /**
     * Sets the value of the strkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRKEY(String value) {
        this.strkey = value;
    }

}
