//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:00 AM MESZ 
//


package de.og.orgdatenreader.orgd.bediener;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BED_KENNUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BED_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="BED_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BED_PASSWORT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BED_VORNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Format")
public class Format {

    @XmlAttribute(name = "BED_KENNUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bedkennung;
    @XmlAttribute(name = "BED_KEY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bedkey;
    @XmlAttribute(name = "BED_NAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bedname;
    @XmlAttribute(name = "BED_PASSWORT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bedpasswort;
    @XmlAttribute(name = "BED_VORNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bedvorname;

    /**
     * Gets the value of the bedkennung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEDKENNUNG() {
        return bedkennung;
    }

    /**
     * Sets the value of the bedkennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEDKENNUNG(String value) {
        this.bedkennung = value;
    }

    /**
     * Gets the value of the bedkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEDKEY() {
        return bedkey;
    }

    /**
     * Sets the value of the bedkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEDKEY(String value) {
        this.bedkey = value;
    }

    /**
     * Gets the value of the bedname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEDNAME() {
        return bedname;
    }

    /**
     * Sets the value of the bedname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEDNAME(String value) {
        this.bedname = value;
    }

    /**
     * Gets the value of the bedpasswort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEDPASSWORT() {
        return bedpasswort;
    }

    /**
     * Sets the value of the bedpasswort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEDPASSWORT(String value) {
        this.bedpasswort = value;
    }

    /**
     * Gets the value of the bedvorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEDVORNAME() {
        return bedvorname;
    }

    /**
     * Sets the value of the bedvorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEDVORNAME(String value) {
        this.bedvorname = value;
    }

}
