//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:00 AM MESZ 
//


package de.og.orgdatenreader.orgd.farben;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FARBE_DRUCKER_B" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_DRUCKER_G" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_DRUCKER_R" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_MONITOR_B" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_MONITOR_G" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_MONITOR_R" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FARBE_PLOTTER_B" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_PLOTTER_G" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FARBE_PLOTTER_R" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Format")
public class Format {

    @XmlAttribute(name = "FARBE_DRUCKER_B", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbedruckerb;
    @XmlAttribute(name = "FARBE_DRUCKER_G", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbedruckerg;
    @XmlAttribute(name = "FARBE_DRUCKER_R", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbedruckerr;
    @XmlAttribute(name = "FARBE_KEY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbekey;
    @XmlAttribute(name = "FARBE_MONITOR_B", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbemonitorb;
    @XmlAttribute(name = "FARBE_MONITOR_G", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbemonitorg;
    @XmlAttribute(name = "FARBE_MONITOR_R", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbemonitorr;
    @XmlAttribute(name = "FARBE_NAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String farbename;
    @XmlAttribute(name = "FARBE_PLOTTER_B", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbeplotterb;
    @XmlAttribute(name = "FARBE_PLOTTER_G", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbeplotterg;
    @XmlAttribute(name = "FARBE_PLOTTER_R", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbeplotterr;

    /**
     * Gets the value of the farbedruckerb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEDRUCKERB() {
        return farbedruckerb;
    }

    /**
     * Sets the value of the farbedruckerb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEDRUCKERB(String value) {
        this.farbedruckerb = value;
    }

    /**
     * Gets the value of the farbedruckerg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEDRUCKERG() {
        return farbedruckerg;
    }

    /**
     * Sets the value of the farbedruckerg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEDRUCKERG(String value) {
        this.farbedruckerg = value;
    }

    /**
     * Gets the value of the farbedruckerr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEDRUCKERR() {
        return farbedruckerr;
    }

    /**
     * Sets the value of the farbedruckerr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEDRUCKERR(String value) {
        this.farbedruckerr = value;
    }

    /**
     * Gets the value of the farbekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEKEY() {
        return farbekey;
    }

    /**
     * Sets the value of the farbekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEKEY(String value) {
        this.farbekey = value;
    }

    /**
     * Gets the value of the farbemonitorb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEMONITORB() {
        return farbemonitorb;
    }

    /**
     * Sets the value of the farbemonitorb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEMONITORB(String value) {
        this.farbemonitorb = value;
    }

    /**
     * Gets the value of the farbemonitorg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEMONITORG() {
        return farbemonitorg;
    }

    /**
     * Sets the value of the farbemonitorg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEMONITORG(String value) {
        this.farbemonitorg = value;
    }

    /**
     * Gets the value of the farbemonitorr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEMONITORR() {
        return farbemonitorr;
    }

    /**
     * Sets the value of the farbemonitorr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEMONITORR(String value) {
        this.farbemonitorr = value;
    }

    /**
     * Gets the value of the farbename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBENAME() {
        return farbename;
    }

    /**
     * Sets the value of the farbename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBENAME(String value) {
        this.farbename = value;
    }

    /**
     * Gets the value of the farbeplotterb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEPLOTTERB() {
        return farbeplotterb;
    }

    /**
     * Sets the value of the farbeplotterb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEPLOTTERB(String value) {
        this.farbeplotterb = value;
    }

    /**
     * Gets the value of the farbeplotterg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEPLOTTERG() {
        return farbeplotterg;
    }

    /**
     * Sets the value of the farbeplotterg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEPLOTTERG(String value) {
        this.farbeplotterg = value;
    }

    /**
     * Gets the value of the farbeplotterr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEPLOTTERR() {
        return farbeplotterr;
    }

    /**
     * Sets the value of the farbeplotterr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEPLOTTERR(String value) {
        this.farbeplotterr = value;
    }

}
