//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:00 AM MESZ 
//


package de.og.orgdatenreader.orgd.farben;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FARBE_DRUCKER_B" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_DRUCKER_G" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_DRUCKER_R" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_MONITOR_B" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_MONITOR_G" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_MONITOR_R" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FARBE_PLOTTER_B" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_PLOTTER_G" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FARBE_PLOTTER_R" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ORGT_FARBEN")
public class ORGTFARBEN {

    @XmlAttribute(name = "FARBE_DRUCKER_B", required = true)
    protected BigInteger farbedruckerb;
    @XmlAttribute(name = "FARBE_DRUCKER_G", required = true)
    protected BigInteger farbedruckerg;
    @XmlAttribute(name = "FARBE_DRUCKER_R", required = true)
    protected BigInteger farbedruckerr;
    @XmlAttribute(name = "FARBE_KEY", required = true)
    protected BigInteger farbekey;
    @XmlAttribute(name = "FARBE_MONITOR_B", required = true)
    protected BigInteger farbemonitorb;
    @XmlAttribute(name = "FARBE_MONITOR_G", required = true)
    protected BigInteger farbemonitorg;
    @XmlAttribute(name = "FARBE_MONITOR_R", required = true)
    protected BigInteger farbemonitorr;
    @XmlAttribute(name = "FARBE_NAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String farbename;
    @XmlAttribute(name = "FARBE_PLOTTER_B", required = true)
    protected BigInteger farbeplotterb;
    @XmlAttribute(name = "FARBE_PLOTTER_G", required = true)
    protected BigInteger farbeplotterg;
    @XmlAttribute(name = "FARBE_PLOTTER_R", required = true)
    protected BigInteger farbeplotterr;

    /**
     * Gets the value of the farbedruckerb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEDRUCKERB() {
        return farbedruckerb;
    }

    /**
     * Sets the value of the farbedruckerb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEDRUCKERB(BigInteger value) {
        this.farbedruckerb = value;
    }

    /**
     * Gets the value of the farbedruckerg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEDRUCKERG() {
        return farbedruckerg;
    }

    /**
     * Sets the value of the farbedruckerg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEDRUCKERG(BigInteger value) {
        this.farbedruckerg = value;
    }

    /**
     * Gets the value of the farbedruckerr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEDRUCKERR() {
        return farbedruckerr;
    }

    /**
     * Sets the value of the farbedruckerr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEDRUCKERR(BigInteger value) {
        this.farbedruckerr = value;
    }

    /**
     * Gets the value of the farbekey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEKEY() {
        return farbekey;
    }

    /**
     * Sets the value of the farbekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEKEY(BigInteger value) {
        this.farbekey = value;
    }

    /**
     * Gets the value of the farbemonitorb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEMONITORB() {
        return farbemonitorb;
    }

    /**
     * Sets the value of the farbemonitorb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEMONITORB(BigInteger value) {
        this.farbemonitorb = value;
    }

    /**
     * Gets the value of the farbemonitorg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEMONITORG() {
        return farbemonitorg;
    }

    /**
     * Sets the value of the farbemonitorg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEMONITORG(BigInteger value) {
        this.farbemonitorg = value;
    }

    /**
     * Gets the value of the farbemonitorr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEMONITORR() {
        return farbemonitorr;
    }

    /**
     * Sets the value of the farbemonitorr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEMONITORR(BigInteger value) {
        this.farbemonitorr = value;
    }

    /**
     * Gets the value of the farbename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBENAME() {
        return farbename;
    }

    /**
     * Sets the value of the farbename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBENAME(String value) {
        this.farbename = value;
    }

    /**
     * Gets the value of the farbeplotterb property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEPLOTTERB() {
        return farbeplotterb;
    }

    /**
     * Sets the value of the farbeplotterb property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEPLOTTERB(BigInteger value) {
        this.farbeplotterb = value;
    }

    /**
     * Gets the value of the farbeplotterg property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEPLOTTERG() {
        return farbeplotterg;
    }

    /**
     * Sets the value of the farbeplotterg property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEPLOTTERG(BigInteger value) {
        this.farbeplotterg = value;
    }

    /**
     * Gets the value of the farbeplotterr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFARBEPLOTTERR() {
        return farbeplotterr;
    }

    /**
     * Sets the value of the farbeplotterr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFARBEPLOTTERR(BigInteger value) {
        this.farbeplotterr = value;
    }

}
