//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:01 AM MESZ 
//


package de.og.orgdatenreader.orgd.strichdefinitionen;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="STRICH_ART" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRICH_GILT_FUER_CODE" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRICH_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRICH_MUSTER" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRICH_STAERKE" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ORGT_STRICHDEFINITIONEN")
public class ORGTSTRICHDEFINITIONEN {

    @XmlAttribute(name = "STRICH_ART", required = true)
    protected BigInteger strichart;
    @XmlAttribute(name = "STRICH_GILT_FUER_CODE", required = true)
    protected BigInteger strichgiltfuercode;
    @XmlAttribute(name = "STRICH_KEY", required = true)
    protected BigInteger strichkey;
    @XmlAttribute(name = "STRICH_MUSTER", required = true)
    protected BigInteger strichmuster;
    @XmlAttribute(name = "STRICH_STAERKE", required = true)
    protected BigInteger strichstaerke;

    /**
     * Gets the value of the strichart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRICHART() {
        return strichart;
    }

    /**
     * Sets the value of the strichart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRICHART(BigInteger value) {
        this.strichart = value;
    }

    /**
     * Gets the value of the strichgiltfuercode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRICHGILTFUERCODE() {
        return strichgiltfuercode;
    }

    /**
     * Sets the value of the strichgiltfuercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRICHGILTFUERCODE(BigInteger value) {
        this.strichgiltfuercode = value;
    }

    /**
     * Gets the value of the strichkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRICHKEY() {
        return strichkey;
    }

    /**
     * Sets the value of the strichkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRICHKEY(BigInteger value) {
        this.strichkey = value;
    }

    /**
     * Gets the value of the strichmuster property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRICHMUSTER() {
        return strichmuster;
    }

    /**
     * Sets the value of the strichmuster property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRICHMUSTER(BigInteger value) {
        this.strichmuster = value;
    }

    /**
     * Gets the value of the strichstaerke property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRICHSTAERKE() {
        return strichstaerke;
    }

    /**
     * Sets the value of the strichstaerke property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRICHSTAERKE(BigInteger value) {
        this.strichstaerke = value;
    }

}
