//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:01 AM MESZ 
//


package de.og.orgdatenreader.orgd.sybolischefarben;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FARBE_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SYMFARB_ENUM" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SYMFARB_KENNUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SYMFARB_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SYMFARB_NAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Format")
public class Format {

    @XmlAttribute(name = "FARBE_KEY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String farbekey;
    @XmlAttribute(name = "SYMFARB_ENUM", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String symfarbenum;
    @XmlAttribute(name = "SYMFARB_KENNUNG", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String symfarbkennung;
    @XmlAttribute(name = "SYMFARB_KEY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String symfarbkey;
    @XmlAttribute(name = "SYMFARB_NAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String symfarbname;

    /**
     * Gets the value of the farbekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFARBEKEY() {
        return farbekey;
    }

    /**
     * Sets the value of the farbekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFARBEKEY(String value) {
        this.farbekey = value;
    }

    /**
     * Gets the value of the symfarbenum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYMFARBENUM() {
        return symfarbenum;
    }

    /**
     * Sets the value of the symfarbenum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYMFARBENUM(String value) {
        this.symfarbenum = value;
    }

    /**
     * Gets the value of the symfarbkennung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYMFARBKENNUNG() {
        return symfarbkennung;
    }

    /**
     * Sets the value of the symfarbkennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYMFARBKENNUNG(String value) {
        this.symfarbkennung = value;
    }

    /**
     * Gets the value of the symfarbkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYMFARBKEY() {
        return symfarbkey;
    }

    /**
     * Sets the value of the symfarbkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYMFARBKEY(String value) {
        this.symfarbkey = value;
    }

    /**
     * Gets the value of the symfarbname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYMFARBNAME() {
        return symfarbname;
    }

    /**
     * Sets the value of the symfarbname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYMFARBNAME(String value) {
        this.symfarbname = value;
    }

}
