//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:06 AM MESZ 
//


package de.og.orgdatenreader.infra.durchgangsknoten;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ABW_BTRST_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BOGEN_RADIUS_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BOGEN_RADIUS_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BPKT_POSITION_X" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BPKT_POSITION_X_LEIDAS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BPKT_POSITION_Y" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BPKT_POSITION_Y_LEIDAS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BRWEG_WERT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BSTGKNT_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BUE_BAUART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BUE_LAENGE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BUE_STRASSENART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BUE_UEBERWACH_ART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="DGKN_TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="FSTRGR_BAUART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FSTRGR_FORTSCHALTENTFERNUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FSTRGR_FORTSCHALTUNG_ZUGENDE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FSTRGR_IST_ZL_SIGNAL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FSTRGR_SIGNALGRUPPE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FZMP_GLEIS_BEZ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FZMP_GLEIS_BEZ_EXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FZMP_GLEIS_WIRKUNGSRICHTUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="FZSS_FAHRSTRASSEN_AUFLOESEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="GLBZN_BEZ_EXT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="GLBZN_GLEIS_BEZ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HPL_GLEIS_BEZ" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HPL_GLEIS_BEZ_EXTERN" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HPL_NUTZLAENGE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HSIG_DWEG_AUFLOESEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="HSIG_STANDORTART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LZBBERKW_MNEIG_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LZBBERKW_MNEIG_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LZBELEM_MASSGEBENDE_NEIGUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="LZBTAF_FS_BILDEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MNEIG_GEFAELLE" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="MNEIG_STEIGUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NBGL_LFD_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NBGL_TYP" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NEIG_NEIGUNG_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="NEIG_NEIGUNG_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OLSG_BZ_BZN_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OLSG_BZ_BZN_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OLSG_NAME_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="OLSG_NAME_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="RIABKN_WIRKUNGSRICHTUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SHSIG_DWEG_AUFLOESEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SHSIG_FS_BILDEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SPLKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRKLAS_KEY_HAT_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRKLAS_KEY_HAT_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWBUEART_KEY_GEHOERT_ZU" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWFWPKTA_KEYHAT_ALS_HAUPTSIG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWFWPKTA_KEYHAT_ALS_VORSIG" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWGLBETRZU_KEY_HAT_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWGLBETRZU_KEY_HAT_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWGLZUS_KEY_HAT_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWGLZUS_KEY_HAT_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SZSS_FS_AUFLOESEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TUNNEL_QUERSCHNITT_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="TUNNEL_QUERSCHNITT_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="VSIG_FAHRSTRASSEN_BILDEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="VSIG_STANDORTART" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ZF_KEY_HAT_FALLEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ZF_KEY_HAT_STEIGEND" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ZNMA_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ZWHALT_HALTEZEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DURCHGANGSKNOTEN")
public class DURCHGANGSKNOTEN {

    @XmlAttribute(name = "ABW_BTRST_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String abwbtrstkey;
    @XmlAttribute(name = "BOGEN_RADIUS_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bogenradiusfallend;
    @XmlAttribute(name = "BOGEN_RADIUS_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bogenradiussteigend;
    @XmlAttribute(name = "BPKT_POSITION_X", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bpktpositionx;
    @XmlAttribute(name = "BPKT_POSITION_X_LEIDAS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bpktpositionxleidas;
    @XmlAttribute(name = "BPKT_POSITION_Y", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bpktpositiony;
    @XmlAttribute(name = "BPKT_POSITION_Y_LEIDAS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bpktpositionyleidas;
    @XmlAttribute(name = "BRWEG_WERT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String brwegwert;
    @XmlAttribute(name = "BSTGKNT_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bstgkntkey;
    @XmlAttribute(name = "BUE_BAUART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String buebauart;
    @XmlAttribute(name = "BUE_LAENGE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String buelaenge;
    @XmlAttribute(name = "BUE_STRASSENART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String buestrassenart;
    @XmlAttribute(name = "BUE_UEBERWACH_ART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bueueberwachart;
    @XmlAttribute(name = "DGKN_TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dgkntype;
    @XmlAttribute(name = "FSTRGR_BAUART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fstrgrbauart;
    @XmlAttribute(name = "FSTRGR_FORTSCHALTENTFERNUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fstrgrfortschaltentfernung;
    @XmlAttribute(name = "FSTRGR_FORTSCHALTUNG_ZUGENDE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fstrgrfortschaltungzugende;
    @XmlAttribute(name = "FSTRGR_IST_ZL_SIGNAL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fstrgristzlsignal;
    @XmlAttribute(name = "FSTRGR_SIGNALGRUPPE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fstrgrsignalgruppe;
    @XmlAttribute(name = "FZMP_GLEIS_BEZ", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fzmpgleisbez;
    @XmlAttribute(name = "FZMP_GLEIS_BEZ_EXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fzmpgleisbezext;
    @XmlAttribute(name = "FZMP_GLEIS_WIRKUNGSRICHTUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fzmpgleiswirkungsrichtung;
    @XmlAttribute(name = "FZSS_FAHRSTRASSEN_AUFLOESEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String fzssfahrstrassenaufloesezeit;
    @XmlAttribute(name = "GLBZN_BEZ_EXT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String glbznbezext;
    @XmlAttribute(name = "GLBZN_GLEIS_BEZ", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String glbzngleisbez;
    @XmlAttribute(name = "HPL_GLEIS_BEZ", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hplgleisbez;
    @XmlAttribute(name = "HPL_GLEIS_BEZ_EXTERN", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hplgleisbezextern;
    @XmlAttribute(name = "HPL_NUTZLAENGE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hplnutzlaenge;
    @XmlAttribute(name = "HSIG_DWEG_AUFLOESEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hsigdwegaufloesezeit;
    @XmlAttribute(name = "HSIG_STANDORTART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String hsigstandortart;
    @XmlAttribute(name = "LZBBERKW_MNEIG_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lzbberkwmneigfallend;
    @XmlAttribute(name = "LZBBERKW_MNEIG_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lzbberkwmneigsteigend;
    @XmlAttribute(name = "LZBELEM_MASSGEBENDE_NEIGUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lzbelemmassgebendeneigung;
    @XmlAttribute(name = "LZBTAF_FS_BILDEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lzbtaffsbildezeit;
    @XmlAttribute(name = "MNEIG_GEFAELLE", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String mneiggefaelle;
    @XmlAttribute(name = "MNEIG_STEIGUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String mneigsteigung;
    @XmlAttribute(name = "NBGL_LFD_NR", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String nbgllfdnr;
    @XmlAttribute(name = "NBGL_TYP", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String nbgltyp;
    @XmlAttribute(name = "NEIG_NEIGUNG_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String neigneigungfallend;
    @XmlAttribute(name = "NEIG_NEIGUNG_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String neigneigungsteigend;
    @XmlAttribute(name = "OLSG_BZ_BZN_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String olsgbzbznfallend;
    @XmlAttribute(name = "OLSG_BZ_BZN_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String olsgbzbznsteigend;
    @XmlAttribute(name = "OLSG_NAME_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String olsgnamefallend;
    @XmlAttribute(name = "OLSG_NAME_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String olsgnamesteigend;
    @XmlAttribute(name = "RIABKN_WIRKUNGSRICHTUNG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String riabknwirkungsrichtung;
    @XmlAttribute(name = "SHSIG_DWEG_AUFLOESEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String shsigdwegaufloesezeit;
    @XmlAttribute(name = "SHSIG_FS_BILDEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String shsigfsbildezeit;
    @XmlAttribute(name = "SPLKN_KEY", required = true)
    protected BigInteger splknkey;
    @XmlAttribute(name = "STRKLAS_KEY_HAT_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strklaskeyhatfallend;
    @XmlAttribute(name = "STRKLAS_KEY_HAT_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strklaskeyhatsteigend;
    @XmlAttribute(name = "SWBUEART_KEY_GEHOERT_ZU", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swbueartkeygehoertzu;
    @XmlAttribute(name = "SWFWPKTA_KEYHAT_ALS_HAUPTSIG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swfwpktakeyhatalshauptsig;
    @XmlAttribute(name = "SWFWPKTA_KEYHAT_ALS_VORSIG", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swfwpktakeyhatalsvorsig;
    @XmlAttribute(name = "SWGLBETRZU_KEY_HAT_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swglbetrzukeyhatfallend;
    @XmlAttribute(name = "SWGLBETRZU_KEY_HAT_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swglbetrzukeyhatsteigend;
    @XmlAttribute(name = "SWGLZUS_KEY_HAT_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swglzuskeyhatfallend;
    @XmlAttribute(name = "SWGLZUS_KEY_HAT_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swglzuskeyhatsteigend;
    @XmlAttribute(name = "SZSS_FS_AUFLOESEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String szssfsaufloesezeit;
    @XmlAttribute(name = "TUNNEL_QUERSCHNITT_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tunnelquerschnittfallend;
    @XmlAttribute(name = "TUNNEL_QUERSCHNITT_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String tunnelquerschnittsteigend;
    @XmlAttribute(name = "VSIG_FAHRSTRASSEN_BILDEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String vsigfahrstrassenbildezeit;
    @XmlAttribute(name = "VSIG_STANDORTART", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String vsigstandortart;
    @XmlAttribute(name = "ZF_KEY_HAT_FALLEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String zfkeyhatfallend;
    @XmlAttribute(name = "ZF_KEY_HAT_STEIGEND", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String zfkeyhatsteigend;
    @XmlAttribute(name = "ZNMA_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String znmakey;
    @XmlAttribute(name = "ZWHALT_HALTEZEIT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String zwhalthaltezeit;

    /**
     * Gets the value of the abwbtrstkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABWBTRSTKEY() {
        return abwbtrstkey;
    }

    /**
     * Sets the value of the abwbtrstkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABWBTRSTKEY(String value) {
        this.abwbtrstkey = value;
    }

    /**
     * Gets the value of the bogenradiusfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOGENRADIUSFALLEND() {
        return bogenradiusfallend;
    }

    /**
     * Sets the value of the bogenradiusfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOGENRADIUSFALLEND(String value) {
        this.bogenradiusfallend = value;
    }

    /**
     * Gets the value of the bogenradiussteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOGENRADIUSSTEIGEND() {
        return bogenradiussteigend;
    }

    /**
     * Sets the value of the bogenradiussteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOGENRADIUSSTEIGEND(String value) {
        this.bogenradiussteigend = value;
    }

    /**
     * Gets the value of the bpktpositionx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBPKTPOSITIONX() {
        return bpktpositionx;
    }

    /**
     * Sets the value of the bpktpositionx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBPKTPOSITIONX(String value) {
        this.bpktpositionx = value;
    }

    /**
     * Gets the value of the bpktpositionxleidas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBPKTPOSITIONXLEIDAS() {
        return bpktpositionxleidas;
    }

    /**
     * Sets the value of the bpktpositionxleidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBPKTPOSITIONXLEIDAS(String value) {
        this.bpktpositionxleidas = value;
    }

    /**
     * Gets the value of the bpktpositiony property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBPKTPOSITIONY() {
        return bpktpositiony;
    }

    /**
     * Sets the value of the bpktpositiony property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBPKTPOSITIONY(String value) {
        this.bpktpositiony = value;
    }

    /**
     * Gets the value of the bpktpositionyleidas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBPKTPOSITIONYLEIDAS() {
        return bpktpositionyleidas;
    }

    /**
     * Sets the value of the bpktpositionyleidas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBPKTPOSITIONYLEIDAS(String value) {
        this.bpktpositionyleidas = value;
    }

    /**
     * Gets the value of the brwegwert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRWEGWERT() {
        return brwegwert;
    }

    /**
     * Sets the value of the brwegwert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRWEGWERT(String value) {
        this.brwegwert = value;
    }

    /**
     * Gets the value of the bstgkntkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBSTGKNTKEY() {
        return bstgkntkey;
    }

    /**
     * Sets the value of the bstgkntkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBSTGKNTKEY(String value) {
        this.bstgkntkey = value;
    }

    /**
     * Gets the value of the buebauart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUEBAUART() {
        return buebauart;
    }

    /**
     * Sets the value of the buebauart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUEBAUART(String value) {
        this.buebauart = value;
    }

    /**
     * Gets the value of the buelaenge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUELAENGE() {
        return buelaenge;
    }

    /**
     * Sets the value of the buelaenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUELAENGE(String value) {
        this.buelaenge = value;
    }

    /**
     * Gets the value of the buestrassenart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUESTRASSENART() {
        return buestrassenart;
    }

    /**
     * Sets the value of the buestrassenart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUESTRASSENART(String value) {
        this.buestrassenart = value;
    }

    /**
     * Gets the value of the bueueberwachart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUEUEBERWACHART() {
        return bueueberwachart;
    }

    /**
     * Sets the value of the bueueberwachart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUEUEBERWACHART(String value) {
        this.bueueberwachart = value;
    }

    /**
     * Gets the value of the dgkntype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGKNTYPE() {
        return dgkntype;
    }

    /**
     * Sets the value of the dgkntype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGKNTYPE(String value) {
        this.dgkntype = value;
    }

    /**
     * Gets the value of the fstrgrbauart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSTRGRBAUART() {
        return fstrgrbauart;
    }

    /**
     * Sets the value of the fstrgrbauart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSTRGRBAUART(String value) {
        this.fstrgrbauart = value;
    }

    /**
     * Gets the value of the fstrgrfortschaltentfernung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSTRGRFORTSCHALTENTFERNUNG() {
        return fstrgrfortschaltentfernung;
    }

    /**
     * Sets the value of the fstrgrfortschaltentfernung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSTRGRFORTSCHALTENTFERNUNG(String value) {
        this.fstrgrfortschaltentfernung = value;
    }

    /**
     * Gets the value of the fstrgrfortschaltungzugende property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSTRGRFORTSCHALTUNGZUGENDE() {
        return fstrgrfortschaltungzugende;
    }

    /**
     * Sets the value of the fstrgrfortschaltungzugende property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSTRGRFORTSCHALTUNGZUGENDE(String value) {
        this.fstrgrfortschaltungzugende = value;
    }

    /**
     * Gets the value of the fstrgristzlsignal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSTRGRISTZLSIGNAL() {
        return fstrgristzlsignal;
    }

    /**
     * Sets the value of the fstrgristzlsignal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSTRGRISTZLSIGNAL(String value) {
        this.fstrgristzlsignal = value;
    }

    /**
     * Gets the value of the fstrgrsignalgruppe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFSTRGRSIGNALGRUPPE() {
        return fstrgrsignalgruppe;
    }

    /**
     * Sets the value of the fstrgrsignalgruppe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFSTRGRSIGNALGRUPPE(String value) {
        this.fstrgrsignalgruppe = value;
    }

    /**
     * Gets the value of the fzmpgleisbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFZMPGLEISBEZ() {
        return fzmpgleisbez;
    }

    /**
     * Sets the value of the fzmpgleisbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFZMPGLEISBEZ(String value) {
        this.fzmpgleisbez = value;
    }

    /**
     * Gets the value of the fzmpgleisbezext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFZMPGLEISBEZEXT() {
        return fzmpgleisbezext;
    }

    /**
     * Sets the value of the fzmpgleisbezext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFZMPGLEISBEZEXT(String value) {
        this.fzmpgleisbezext = value;
    }

    /**
     * Gets the value of the fzmpgleiswirkungsrichtung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFZMPGLEISWIRKUNGSRICHTUNG() {
        return fzmpgleiswirkungsrichtung;
    }

    /**
     * Sets the value of the fzmpgleiswirkungsrichtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFZMPGLEISWIRKUNGSRICHTUNG(String value) {
        this.fzmpgleiswirkungsrichtung = value;
    }

    /**
     * Gets the value of the fzssfahrstrassenaufloesezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFZSSFAHRSTRASSENAUFLOESEZEIT() {
        return fzssfahrstrassenaufloesezeit;
    }

    /**
     * Sets the value of the fzssfahrstrassenaufloesezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFZSSFAHRSTRASSENAUFLOESEZEIT(String value) {
        this.fzssfahrstrassenaufloesezeit = value;
    }

    /**
     * Gets the value of the glbznbezext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLBZNBEZEXT() {
        return glbznbezext;
    }

    /**
     * Sets the value of the glbznbezext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLBZNBEZEXT(String value) {
        this.glbznbezext = value;
    }

    /**
     * Gets the value of the glbzngleisbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLBZNGLEISBEZ() {
        return glbzngleisbez;
    }

    /**
     * Sets the value of the glbzngleisbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLBZNGLEISBEZ(String value) {
        this.glbzngleisbez = value;
    }

    /**
     * Gets the value of the hplgleisbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPLGLEISBEZ() {
        return hplgleisbez;
    }

    /**
     * Sets the value of the hplgleisbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPLGLEISBEZ(String value) {
        this.hplgleisbez = value;
    }

    /**
     * Gets the value of the hplgleisbezextern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPLGLEISBEZEXTERN() {
        return hplgleisbezextern;
    }

    /**
     * Sets the value of the hplgleisbezextern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPLGLEISBEZEXTERN(String value) {
        this.hplgleisbezextern = value;
    }

    /**
     * Gets the value of the hplnutzlaenge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPLNUTZLAENGE() {
        return hplnutzlaenge;
    }

    /**
     * Sets the value of the hplnutzlaenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPLNUTZLAENGE(String value) {
        this.hplnutzlaenge = value;
    }

    /**
     * Gets the value of the hsigdwegaufloesezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSIGDWEGAUFLOESEZEIT() {
        return hsigdwegaufloesezeit;
    }

    /**
     * Sets the value of the hsigdwegaufloesezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSIGDWEGAUFLOESEZEIT(String value) {
        this.hsigdwegaufloesezeit = value;
    }

    /**
     * Gets the value of the hsigstandortart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHSIGSTANDORTART() {
        return hsigstandortart;
    }

    /**
     * Sets the value of the hsigstandortart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHSIGSTANDORTART(String value) {
        this.hsigstandortart = value;
    }

    /**
     * Gets the value of the lzbberkwmneigfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLZBBERKWMNEIGFALLEND() {
        return lzbberkwmneigfallend;
    }

    /**
     * Sets the value of the lzbberkwmneigfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLZBBERKWMNEIGFALLEND(String value) {
        this.lzbberkwmneigfallend = value;
    }

    /**
     * Gets the value of the lzbberkwmneigsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLZBBERKWMNEIGSTEIGEND() {
        return lzbberkwmneigsteigend;
    }

    /**
     * Sets the value of the lzbberkwmneigsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLZBBERKWMNEIGSTEIGEND(String value) {
        this.lzbberkwmneigsteigend = value;
    }

    /**
     * Gets the value of the lzbelemmassgebendeneigung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLZBELEMMASSGEBENDENEIGUNG() {
        return lzbelemmassgebendeneigung;
    }

    /**
     * Sets the value of the lzbelemmassgebendeneigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLZBELEMMASSGEBENDENEIGUNG(String value) {
        this.lzbelemmassgebendeneigung = value;
    }

    /**
     * Gets the value of the lzbtaffsbildezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLZBTAFFSBILDEZEIT() {
        return lzbtaffsbildezeit;
    }

    /**
     * Sets the value of the lzbtaffsbildezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLZBTAFFSBILDEZEIT(String value) {
        this.lzbtaffsbildezeit = value;
    }

    /**
     * Gets the value of the mneiggefaelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMNEIGGEFAELLE() {
        return mneiggefaelle;
    }

    /**
     * Sets the value of the mneiggefaelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMNEIGGEFAELLE(String value) {
        this.mneiggefaelle = value;
    }

    /**
     * Gets the value of the mneigsteigung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMNEIGSTEIGUNG() {
        return mneigsteigung;
    }

    /**
     * Sets the value of the mneigsteigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMNEIGSTEIGUNG(String value) {
        this.mneigsteigung = value;
    }

    /**
     * Gets the value of the nbgllfdnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNBGLLFDNR() {
        return nbgllfdnr;
    }

    /**
     * Sets the value of the nbgllfdnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNBGLLFDNR(String value) {
        this.nbgllfdnr = value;
    }

    /**
     * Gets the value of the nbgltyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNBGLTYP() {
        return nbgltyp;
    }

    /**
     * Sets the value of the nbgltyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNBGLTYP(String value) {
        this.nbgltyp = value;
    }

    /**
     * Gets the value of the neigneigungfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEIGNEIGUNGFALLEND() {
        return neigneigungfallend;
    }

    /**
     * Sets the value of the neigneigungfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEIGNEIGUNGFALLEND(String value) {
        this.neigneigungfallend = value;
    }

    /**
     * Gets the value of the neigneigungsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEIGNEIGUNGSTEIGEND() {
        return neigneigungsteigend;
    }

    /**
     * Sets the value of the neigneigungsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEIGNEIGUNGSTEIGEND(String value) {
        this.neigneigungsteigend = value;
    }

    /**
     * Gets the value of the olsgbzbznfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLSGBZBZNFALLEND() {
        return olsgbzbznfallend;
    }

    /**
     * Sets the value of the olsgbzbznfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLSGBZBZNFALLEND(String value) {
        this.olsgbzbznfallend = value;
    }

    /**
     * Gets the value of the olsgbzbznsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLSGBZBZNSTEIGEND() {
        return olsgbzbznsteigend;
    }

    /**
     * Sets the value of the olsgbzbznsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLSGBZBZNSTEIGEND(String value) {
        this.olsgbzbznsteigend = value;
    }

    /**
     * Gets the value of the olsgnamefallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLSGNAMEFALLEND() {
        return olsgnamefallend;
    }

    /**
     * Sets the value of the olsgnamefallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLSGNAMEFALLEND(String value) {
        this.olsgnamefallend = value;
    }

    /**
     * Gets the value of the olsgnamesteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOLSGNAMESTEIGEND() {
        return olsgnamesteigend;
    }

    /**
     * Sets the value of the olsgnamesteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOLSGNAMESTEIGEND(String value) {
        this.olsgnamesteigend = value;
    }

    /**
     * Gets the value of the riabknwirkungsrichtung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIABKNWIRKUNGSRICHTUNG() {
        return riabknwirkungsrichtung;
    }

    /**
     * Sets the value of the riabknwirkungsrichtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIABKNWIRKUNGSRICHTUNG(String value) {
        this.riabknwirkungsrichtung = value;
    }

    /**
     * Gets the value of the shsigdwegaufloesezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHSIGDWEGAUFLOESEZEIT() {
        return shsigdwegaufloesezeit;
    }

    /**
     * Sets the value of the shsigdwegaufloesezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHSIGDWEGAUFLOESEZEIT(String value) {
        this.shsigdwegaufloesezeit = value;
    }

    /**
     * Gets the value of the shsigfsbildezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHSIGFSBILDEZEIT() {
        return shsigfsbildezeit;
    }

    /**
     * Sets the value of the shsigfsbildezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHSIGFSBILDEZEIT(String value) {
        this.shsigfsbildezeit = value;
    }

    /**
     * Gets the value of the splknkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSPLKNKEY() {
        return splknkey;
    }

    /**
     * Sets the value of the splknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSPLKNKEY(BigInteger value) {
        this.splknkey = value;
    }

    /**
     * Gets the value of the strklaskeyhatfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRKLASKEYHATFALLEND() {
        return strklaskeyhatfallend;
    }

    /**
     * Sets the value of the strklaskeyhatfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRKLASKEYHATFALLEND(String value) {
        this.strklaskeyhatfallend = value;
    }

    /**
     * Gets the value of the strklaskeyhatsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRKLASKEYHATSTEIGEND() {
        return strklaskeyhatsteigend;
    }

    /**
     * Sets the value of the strklaskeyhatsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRKLASKEYHATSTEIGEND(String value) {
        this.strklaskeyhatsteigend = value;
    }

    /**
     * Gets the value of the swbueartkeygehoertzu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWBUEARTKEYGEHOERTZU() {
        return swbueartkeygehoertzu;
    }

    /**
     * Sets the value of the swbueartkeygehoertzu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWBUEARTKEYGEHOERTZU(String value) {
        this.swbueartkeygehoertzu = value;
    }

    /**
     * Gets the value of the swfwpktakeyhatalshauptsig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWFWPKTAKEYHATALSHAUPTSIG() {
        return swfwpktakeyhatalshauptsig;
    }

    /**
     * Sets the value of the swfwpktakeyhatalshauptsig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWFWPKTAKEYHATALSHAUPTSIG(String value) {
        this.swfwpktakeyhatalshauptsig = value;
    }

    /**
     * Gets the value of the swfwpktakeyhatalsvorsig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWFWPKTAKEYHATALSVORSIG() {
        return swfwpktakeyhatalsvorsig;
    }

    /**
     * Sets the value of the swfwpktakeyhatalsvorsig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWFWPKTAKEYHATALSVORSIG(String value) {
        this.swfwpktakeyhatalsvorsig = value;
    }

    /**
     * Gets the value of the swglbetrzukeyhatfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWGLBETRZUKEYHATFALLEND() {
        return swglbetrzukeyhatfallend;
    }

    /**
     * Sets the value of the swglbetrzukeyhatfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWGLBETRZUKEYHATFALLEND(String value) {
        this.swglbetrzukeyhatfallend = value;
    }

    /**
     * Gets the value of the swglbetrzukeyhatsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWGLBETRZUKEYHATSTEIGEND() {
        return swglbetrzukeyhatsteigend;
    }

    /**
     * Sets the value of the swglbetrzukeyhatsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWGLBETRZUKEYHATSTEIGEND(String value) {
        this.swglbetrzukeyhatsteigend = value;
    }

    /**
     * Gets the value of the swglzuskeyhatfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWGLZUSKEYHATFALLEND() {
        return swglzuskeyhatfallend;
    }

    /**
     * Sets the value of the swglzuskeyhatfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWGLZUSKEYHATFALLEND(String value) {
        this.swglzuskeyhatfallend = value;
    }

    /**
     * Gets the value of the swglzuskeyhatsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWGLZUSKEYHATSTEIGEND() {
        return swglzuskeyhatsteigend;
    }

    /**
     * Sets the value of the swglzuskeyhatsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWGLZUSKEYHATSTEIGEND(String value) {
        this.swglzuskeyhatsteigend = value;
    }

    /**
     * Gets the value of the szssfsaufloesezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSZSSFSAUFLOESEZEIT() {
        return szssfsaufloesezeit;
    }

    /**
     * Sets the value of the szssfsaufloesezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSZSSFSAUFLOESEZEIT(String value) {
        this.szssfsaufloesezeit = value;
    }

    /**
     * Gets the value of the tunnelquerschnittfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTUNNELQUERSCHNITTFALLEND() {
        return tunnelquerschnittfallend;
    }

    /**
     * Sets the value of the tunnelquerschnittfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTUNNELQUERSCHNITTFALLEND(String value) {
        this.tunnelquerschnittfallend = value;
    }

    /**
     * Gets the value of the tunnelquerschnittsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTUNNELQUERSCHNITTSTEIGEND() {
        return tunnelquerschnittsteigend;
    }

    /**
     * Sets the value of the tunnelquerschnittsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTUNNELQUERSCHNITTSTEIGEND(String value) {
        this.tunnelquerschnittsteigend = value;
    }

    /**
     * Gets the value of the vsigfahrstrassenbildezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSIGFAHRSTRASSENBILDEZEIT() {
        return vsigfahrstrassenbildezeit;
    }

    /**
     * Sets the value of the vsigfahrstrassenbildezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSIGFAHRSTRASSENBILDEZEIT(String value) {
        this.vsigfahrstrassenbildezeit = value;
    }

    /**
     * Gets the value of the vsigstandortart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSIGSTANDORTART() {
        return vsigstandortart;
    }

    /**
     * Sets the value of the vsigstandortart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSIGSTANDORTART(String value) {
        this.vsigstandortart = value;
    }

    /**
     * Gets the value of the zfkeyhatfallend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZFKEYHATFALLEND() {
        return zfkeyhatfallend;
    }

    /**
     * Sets the value of the zfkeyhatfallend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZFKEYHATFALLEND(String value) {
        this.zfkeyhatfallend = value;
    }

    /**
     * Gets the value of the zfkeyhatsteigend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZFKEYHATSTEIGEND() {
        return zfkeyhatsteigend;
    }

    /**
     * Sets the value of the zfkeyhatsteigend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZFKEYHATSTEIGEND(String value) {
        this.zfkeyhatsteigend = value;
    }

    /**
     * Gets the value of the znmakey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZNMAKEY() {
        return znmakey;
    }

    /**
     * Sets the value of the znmakey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZNMAKEY(String value) {
        this.znmakey = value;
    }

    /**
     * Gets the value of the zwhalthaltezeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZWHALTHALTEZEIT() {
        return zwhalthaltezeit;
    }

    /**
     * Sets the value of the zwhalthaltezeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZWHALTHALTEZEIT(String value) {
        this.zwhalthaltezeit = value;
    }

}
