//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:03 AM MESZ 
//


package de.og.orgdatenreader.infra.strecken;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="STR_EXTERN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STR_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STR_KURZNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STR_NR" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "STRECKEN")
public class STRECKEN {

    @XmlAttribute(name = "STR_EXTERN_KEY", required = true)
    protected BigInteger strexternkey;
    @XmlAttribute(name = "STR_KEY", required = true)
    protected BigInteger strkey;
    @XmlAttribute(name = "STR_KURZNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strkurzname;
    @XmlAttribute(name = "STR_NR", required = true)
    protected BigInteger strnr;

    /**
     * Gets the value of the strexternkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTREXTERNKEY() {
        return strexternkey;
    }

    /**
     * Sets the value of the strexternkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTREXTERNKEY(BigInteger value) {
        this.strexternkey = value;
    }

    /**
     * Gets the value of the strkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRKEY() {
        return strkey;
    }

    /**
     * Sets the value of the strkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRKEY(BigInteger value) {
        this.strkey = value;
    }

    /**
     * Gets the value of the strkurzname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRKURZNAME() {
        return strkurzname;
    }

    /**
     * Sets the value of the strkurzname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRKURZNAME(String value) {
        this.strkurzname = value;
    }

    /**
     * Gets the value of the strnr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRNR() {
        return strnr;
    }

    /**
     * Sets the value of the strnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRNR(BigInteger value) {
        this.strnr = value;
    }

}
