//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.21 at 11:56:06 AM MESZ 
//


package de.og.orgdatenreader.infra.streckenabschnitte;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BZ_NR_FB_IN_GR" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="BZ_NR_FB_IN_RI" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="EBU_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SPLKN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_BETRIEBSKURZNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_BETRIEBSNAME" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_BTRSTBISZMSTZUSAETZLI" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_BTRSTVONZMSTZUSAETZLI" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_DRUCKERTUECHTIGUNG" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="STRABSCH_EXTERN_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_KM_BIS" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_KM_UEBLBIS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_KM_UEBLVON" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_KM_VON" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_LAENGE" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_LAUFFAEHIGKEIT" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="STRABSCH_NAME11" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="STRABSCH_NOTBREMSUEBERBR" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="STRABSCH_NUMMER" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWFPLGR_KEY_HAT_BTRST_BIS" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWFPLGR_KEY_HAT_BTRST_VON" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWSTRART_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWSTRBART_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRBNZ_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRBSART_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRBTRA_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRBWEIS_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWSTRKAT_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWSTRKLAS_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRQUA_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWSTRSPUR_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="SWSTRZLB_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="SWZLST_KEY" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "STRECKENABSCHNITTE")
public class STRECKENABSCHNITTE {

    @XmlAttribute(name = "BZ_NR_FB_IN_GR", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bznrfbingr;
    @XmlAttribute(name = "BZ_NR_FB_IN_RI", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String bznrfbinri;
    @XmlAttribute(name = "EBU_KEY", required = true)
    protected BigInteger ebukey;
    @XmlAttribute(name = "SPLKN_KEY", required = true)
    protected BigInteger splknkey;
    @XmlAttribute(name = "STRABSCH_BETRIEBSKURZNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschbetriebskurzname;
    @XmlAttribute(name = "STRABSCH_BETRIEBSNAME", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschbetriebsname;
    @XmlAttribute(name = "STRABSCH_BTRSTBISZMSTZUSAETZLI", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschbtrstbiszmstzusaetzli;
    @XmlAttribute(name = "STRABSCH_BTRSTVONZMSTZUSAETZLI", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschbtrstvonzmstzusaetzli;
    @XmlAttribute(name = "STRABSCH_DRUCKERTUECHTIGUNG", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String strabschdruckertuechtigung;
    @XmlAttribute(name = "STRABSCH_EXTERN_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschexternkey;
    @XmlAttribute(name = "STRABSCH_KEY", required = true)
    protected BigInteger strabschkey;
    @XmlAttribute(name = "STRABSCH_KM_BIS", required = true)
    protected BigInteger strabschkmbis;
    @XmlAttribute(name = "STRABSCH_KM_UEBLBIS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschkmueblbis;
    @XmlAttribute(name = "STRABSCH_KM_UEBLVON", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschkmueblvon;
    @XmlAttribute(name = "STRABSCH_KM_VON", required = true)
    protected BigInteger strabschkmvon;
    @XmlAttribute(name = "STRABSCH_LAENGE", required = true)
    protected BigInteger strabschlaenge;
    @XmlAttribute(name = "STRABSCH_LAUFFAEHIGKEIT", required = true)
    protected BigInteger strabschlauffaehigkeit;
    @XmlAttribute(name = "STRABSCH_NAME11", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String strabschname11;
    @XmlAttribute(name = "STRABSCH_NOTBREMSUEBERBR", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String strabschnotbremsueberbr;
    @XmlAttribute(name = "STRABSCH_NUMMER", required = true)
    protected BigInteger strabschnummer;
    @XmlAttribute(name = "SWFPLGR_KEY_HAT_BTRST_BIS", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swfplgrkeyhatbtrstbis;
    @XmlAttribute(name = "SWFPLGR_KEY_HAT_BTRST_VON", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swfplgrkeyhatbtrstvon;
    @XmlAttribute(name = "SWSTRART_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swstrartkey;
    @XmlAttribute(name = "SWSTRBART_KEY", required = true)
    protected BigInteger swstrbartkey;
    @XmlAttribute(name = "SWSTRBNZ_KEY", required = true)
    protected BigInteger swstrbnzkey;
    @XmlAttribute(name = "SWSTRBSART_KEY", required = true)
    protected BigInteger swstrbsartkey;
    @XmlAttribute(name = "SWSTRBTRA_KEY", required = true)
    protected BigInteger swstrbtrakey;
    @XmlAttribute(name = "SWSTRBWEIS_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swstrbweiskey;
    @XmlAttribute(name = "SWSTRKAT_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swstrkatkey;
    @XmlAttribute(name = "SWSTRKLAS_KEY", required = true)
    protected BigInteger swstrklaskey;
    @XmlAttribute(name = "SWSTRQUA_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swstrquakey;
    @XmlAttribute(name = "SWSTRSPUR_KEY", required = true)
    protected BigInteger swstrspurkey;
    @XmlAttribute(name = "SWSTRZLB_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swstrzlbkey;
    @XmlAttribute(name = "SWZLST_KEY", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String swzlstkey;

    /**
     * Gets the value of the bznrfbingr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBZNRFBINGR() {
        return bznrfbingr;
    }

    /**
     * Sets the value of the bznrfbingr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBZNRFBINGR(String value) {
        this.bznrfbingr = value;
    }

    /**
     * Gets the value of the bznrfbinri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBZNRFBINRI() {
        return bznrfbinri;
    }

    /**
     * Sets the value of the bznrfbinri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBZNRFBINRI(String value) {
        this.bznrfbinri = value;
    }

    /**
     * Gets the value of the ebukey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEBUKEY() {
        return ebukey;
    }

    /**
     * Sets the value of the ebukey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEBUKEY(BigInteger value) {
        this.ebukey = value;
    }

    /**
     * Gets the value of the splknkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSPLKNKEY() {
        return splknkey;
    }

    /**
     * Sets the value of the splknkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSPLKNKEY(BigInteger value) {
        this.splknkey = value;
    }

    /**
     * Gets the value of the strabschbetriebskurzname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHBETRIEBSKURZNAME() {
        return strabschbetriebskurzname;
    }

    /**
     * Sets the value of the strabschbetriebskurzname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHBETRIEBSKURZNAME(String value) {
        this.strabschbetriebskurzname = value;
    }

    /**
     * Gets the value of the strabschbetriebsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHBETRIEBSNAME() {
        return strabschbetriebsname;
    }

    /**
     * Sets the value of the strabschbetriebsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHBETRIEBSNAME(String value) {
        this.strabschbetriebsname = value;
    }

    /**
     * Gets the value of the strabschbtrstbiszmstzusaetzli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHBTRSTBISZMSTZUSAETZLI() {
        return strabschbtrstbiszmstzusaetzli;
    }

    /**
     * Sets the value of the strabschbtrstbiszmstzusaetzli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHBTRSTBISZMSTZUSAETZLI(String value) {
        this.strabschbtrstbiszmstzusaetzli = value;
    }

    /**
     * Gets the value of the strabschbtrstvonzmstzusaetzli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHBTRSTVONZMSTZUSAETZLI() {
        return strabschbtrstvonzmstzusaetzli;
    }

    /**
     * Sets the value of the strabschbtrstvonzmstzusaetzli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHBTRSTVONZMSTZUSAETZLI(String value) {
        this.strabschbtrstvonzmstzusaetzli = value;
    }

    /**
     * Gets the value of the strabschdruckertuechtigung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHDRUCKERTUECHTIGUNG() {
        return strabschdruckertuechtigung;
    }

    /**
     * Sets the value of the strabschdruckertuechtigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHDRUCKERTUECHTIGUNG(String value) {
        this.strabschdruckertuechtigung = value;
    }

    /**
     * Gets the value of the strabschexternkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHEXTERNKEY() {
        return strabschexternkey;
    }

    /**
     * Sets the value of the strabschexternkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHEXTERNKEY(String value) {
        this.strabschexternkey = value;
    }

    /**
     * Gets the value of the strabschkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHKEY() {
        return strabschkey;
    }

    /**
     * Sets the value of the strabschkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHKEY(BigInteger value) {
        this.strabschkey = value;
    }

    /**
     * Gets the value of the strabschkmbis property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHKMBIS() {
        return strabschkmbis;
    }

    /**
     * Sets the value of the strabschkmbis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHKMBIS(BigInteger value) {
        this.strabschkmbis = value;
    }

    /**
     * Gets the value of the strabschkmueblbis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHKMUEBLBIS() {
        return strabschkmueblbis;
    }

    /**
     * Sets the value of the strabschkmueblbis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHKMUEBLBIS(String value) {
        this.strabschkmueblbis = value;
    }

    /**
     * Gets the value of the strabschkmueblvon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHKMUEBLVON() {
        return strabschkmueblvon;
    }

    /**
     * Sets the value of the strabschkmueblvon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHKMUEBLVON(String value) {
        this.strabschkmueblvon = value;
    }

    /**
     * Gets the value of the strabschkmvon property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHKMVON() {
        return strabschkmvon;
    }

    /**
     * Sets the value of the strabschkmvon property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHKMVON(BigInteger value) {
        this.strabschkmvon = value;
    }

    /**
     * Gets the value of the strabschlaenge property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHLAENGE() {
        return strabschlaenge;
    }

    /**
     * Sets the value of the strabschlaenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHLAENGE(BigInteger value) {
        this.strabschlaenge = value;
    }

    /**
     * Gets the value of the strabschlauffaehigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHLAUFFAEHIGKEIT() {
        return strabschlauffaehigkeit;
    }

    /**
     * Sets the value of the strabschlauffaehigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHLAUFFAEHIGKEIT(BigInteger value) {
        this.strabschlauffaehigkeit = value;
    }

    /**
     * Gets the value of the strabschname11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHNAME11() {
        return strabschname11;
    }

    /**
     * Sets the value of the strabschname11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHNAME11(String value) {
        this.strabschname11 = value;
    }

    /**
     * Gets the value of the strabschnotbremsueberbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTRABSCHNOTBREMSUEBERBR() {
        return strabschnotbremsueberbr;
    }

    /**
     * Sets the value of the strabschnotbremsueberbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTRABSCHNOTBREMSUEBERBR(String value) {
        this.strabschnotbremsueberbr = value;
    }

    /**
     * Gets the value of the strabschnummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSTRABSCHNUMMER() {
        return strabschnummer;
    }

    /**
     * Sets the value of the strabschnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSTRABSCHNUMMER(BigInteger value) {
        this.strabschnummer = value;
    }

    /**
     * Gets the value of the swfplgrkeyhatbtrstbis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWFPLGRKEYHATBTRSTBIS() {
        return swfplgrkeyhatbtrstbis;
    }

    /**
     * Sets the value of the swfplgrkeyhatbtrstbis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWFPLGRKEYHATBTRSTBIS(String value) {
        this.swfplgrkeyhatbtrstbis = value;
    }

    /**
     * Gets the value of the swfplgrkeyhatbtrstvon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWFPLGRKEYHATBTRSTVON() {
        return swfplgrkeyhatbtrstvon;
    }

    /**
     * Sets the value of the swfplgrkeyhatbtrstvon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWFPLGRKEYHATBTRSTVON(String value) {
        this.swfplgrkeyhatbtrstvon = value;
    }

    /**
     * Gets the value of the swstrartkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWSTRARTKEY() {
        return swstrartkey;
    }

    /**
     * Sets the value of the swstrartkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWSTRARTKEY(String value) {
        this.swstrartkey = value;
    }

    /**
     * Gets the value of the swstrbartkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRBARTKEY() {
        return swstrbartkey;
    }

    /**
     * Sets the value of the swstrbartkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRBARTKEY(BigInteger value) {
        this.swstrbartkey = value;
    }

    /**
     * Gets the value of the swstrbnzkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRBNZKEY() {
        return swstrbnzkey;
    }

    /**
     * Sets the value of the swstrbnzkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRBNZKEY(BigInteger value) {
        this.swstrbnzkey = value;
    }

    /**
     * Gets the value of the swstrbsartkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRBSARTKEY() {
        return swstrbsartkey;
    }

    /**
     * Sets the value of the swstrbsartkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRBSARTKEY(BigInteger value) {
        this.swstrbsartkey = value;
    }

    /**
     * Gets the value of the swstrbtrakey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRBTRAKEY() {
        return swstrbtrakey;
    }

    /**
     * Sets the value of the swstrbtrakey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRBTRAKEY(BigInteger value) {
        this.swstrbtrakey = value;
    }

    /**
     * Gets the value of the swstrbweiskey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWSTRBWEISKEY() {
        return swstrbweiskey;
    }

    /**
     * Sets the value of the swstrbweiskey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWSTRBWEISKEY(String value) {
        this.swstrbweiskey = value;
    }

    /**
     * Gets the value of the swstrkatkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWSTRKATKEY() {
        return swstrkatkey;
    }

    /**
     * Sets the value of the swstrkatkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWSTRKATKEY(String value) {
        this.swstrkatkey = value;
    }

    /**
     * Gets the value of the swstrklaskey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRKLASKEY() {
        return swstrklaskey;
    }

    /**
     * Sets the value of the swstrklaskey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRKLASKEY(BigInteger value) {
        this.swstrklaskey = value;
    }

    /**
     * Gets the value of the swstrquakey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWSTRQUAKEY() {
        return swstrquakey;
    }

    /**
     * Sets the value of the swstrquakey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWSTRQUAKEY(String value) {
        this.swstrquakey = value;
    }

    /**
     * Gets the value of the swstrspurkey property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSWSTRSPURKEY() {
        return swstrspurkey;
    }

    /**
     * Sets the value of the swstrspurkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSWSTRSPURKEY(BigInteger value) {
        this.swstrspurkey = value;
    }

    /**
     * Gets the value of the swstrzlbkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWSTRZLBKEY() {
        return swstrzlbkey;
    }

    /**
     * Sets the value of the swstrzlbkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWSTRZLBKEY(String value) {
        this.swstrzlbkey = value;
    }

    /**
     * Gets the value of the swzlstkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWZLSTKEY() {
        return swzlstkey;
    }

    /**
     * Sets the value of the swzlstkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWZLSTKEY(String value) {
        this.swzlstkey = value;
    }

}
